### PR TITLE
Files associated with R2S Step2

### LINKED ISSUE #21: Run ALARA
Run ALARA with files generated in #20.

Should not require much, if any, additional information.

### PR DESCRIPTION
**Pull request by anu1217**
fixes #21 

-- Adding input files needed for Step 2 of R2S
-- The irradiation schedule was changed in the ALARA input file created in Step 1 to match the parameters specified in OpenMC
-- The config file is the same as the one in #25

### CODE REVIEW

**Review by gonuke — CHANGES_REQUESTED** [review]
I assume this gets set in the `config.ini` but you probably want a larger source normalization. This has 1e10 for 3e8 seconds (3years).  We have 3.55E17 n/MJ of fusion energy, or a source strength of 3.55E17 n/s for each MW of fusion energy. You may want to increase this source normalization to see if that gives you more variation in the photon source over time

**Comment by anu1217** [comment]
> I assume this gets set in the `config.ini` but you probably want a larger source normalization. This has 1e10 for 3e8 seconds (3years). We have 3.55E17 n/MJ of fusion energy, or a source strength of 3.55E17 n/s for each MW of fusion energy. You may want to increase this source normalization to see if that gives you more variation in the photon source over time

The source normalization is set manually in the ALARA input file created by `config.ini` - by default it's set to 1e10. I changed it to 1e18, which results in a larger and more varied photon distribution. However, the mesh distribution created at each of the two decay timesteps is exactly the same (source.h5m), although the number of photons/second emitted (photon_source_intensities.txt) is different. I could add these files here, but I'm not sure if the R2S output belongs in this particular PR.

**Comment by gonuke** [comment]
When I look at the `phtn_src` file, I see evidence that they are different at different shutdown times.

This bash command will only look at the `TOTAL` photon source (rather than the nuclide-specific source), and will exclude the lines for `shutdown`
``` bash
prompt%> grep ^TOTAL phtn_src | grep -v shutdown | less
```
As I scroll through, I see a surprising number of results with 0 photon source (that's maybe a different problem), but most mesh elements that have any photon source have different values at 24 h and 1 month.

How can you tell the two files are the same?

**Comment by gonuke** [comment]
Should these files all be in a subdirectory somewhere?

**Comment by anu1217** [comment]
> Should these files all be in a subdirectory somewhere?

Yes, they've been moved now

**Review by gonuke — APPROVED** [review]
I'm not going to review the contents of these files as it appears that they are all outputs of the R2S process.  Thanks for arranging them well @anu1217

**Pull request merged**
